### ISSUE TITLE
0.3.1 not working on OS X 10.9.5 (Mavericks)

### ISSUE THREAD

**Issue by romaincointepas** [Kagami/boram#11]
After opening a video file:

<img width="1440" alt="screen shot 2017-02-26 at 3 46 18 am" src="https://cloud.githubusercontent.com/assets/797899/23334361/a3ac39ec-fbd7-11e6-8112-bf24886b5e89.png">

**Comment by Kagami** [comment]
Thanks for the report. Seems like ffmpeg needs `--disable-filter=coreimage` configure flag. I will make new build.

**Comment by Kagami** [comment]
Though according to [this table](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/OSX_Technology_Overview/SystemFrameworks/SystemFrameworks.html) it should be available since 10.4.
Does `ls -l /System/Library/Frameworks/CoreImage.framework` return something?

**Comment by Kagami** [comment]
Or maybe it was in `/System/Library/Frameworks/QuartzCore.framework/Versions/A/Frameworks/CoreImage.framework` in old versions of Mac OS, according to Google.
Need to either fix paths, or disable.

Try to extract [ffmpeg-noci.zip](https://github.com/Kagami/boram/files/801536/ffmpeg-noci.zip) inside boram/Resources/app directory. Will it help?

**Comment by romaincointepas** [comment]
Indeed:
```
$ ls -l /System/Library/Frameworks/CoreImage.framework
ls: /System/Library/Frameworks/CoreImage.framework: No such file or directory
```
```
$ ls /System/Library/Frameworks/QuartzCore.framework/Versions/A/Frameworks/CoreImage.framework
CoreImage	Headers		Resources	Versions
```

Extracted (and overwrote) all files from `ffmpeg-noci.zip` inside the `app` folder, there is now a new error when opening a file:
<img width="1440" alt="screen shot 2017-02-26 at 6 11 45 am" src="https://cloud.githubusercontent.com/assets/797899/23335183/9695267a-fbea-11e6-913f-08db0037cd50.png">

**Comment by Kagami** [comment]
Funny, this is fixed 3 days ago: https://github.com/FFmpeg/FFmpeg/commit/dcd3418a35a
Let me rebuild from HEAD and also used fixed path to CoreImage instead.

**Comment by Kagami** [comment]
Try [ffmpeg-cifix-vboxfix.zip](https://github.com/Kagami/boram/files/801595/ffmpeg-cifix-vboxfix.zip)

**Comment by Kagami** [comment]
ping

**Comment by romaincointepas** [comment]
Oh sorry, I missed that notification somehow. Just copied/replaced all files from `ffmpeg-cifix-vboxfix.zip` in the `app` folder, I still get the same error it seems:

<img width="1440" alt="screen shot 2017-02-28 at 10 17 49 pm" src="https://cloud.githubusercontent.com/assets/797899/23408646/c7f0cc68-fe03-11e6-86c3-f6324d6c4e72.png">

**Comment by Kagami** [comment]
You're right, libavcodec.dylib still includes that R_2020 symbol for some reason even though commit above should have been fixed it… Maybe there is another issue.

Recompiled ffmpeg and mpv with --disable-videotoolbox, try [ffmpeg-cifix-novbox.zip](https://github.com/Kagami/boram/files/807279/ffmpeg-cifix-novbox.zip). Better to investigate exact reason, but should be ok as a temporal fix.

>if you intend to support OS X 10.9+, you need to either brew install mpv from OS X 10.9 or build it yourself

I guess it's not mandatory. Just disable use of APIs not availble in earlier versions.

**Comment by romaincointepas** [comment]
Works great, that solved it!

What version of OS X are you using to build interop.cc?

**Comment by Kagami** [comment]
Sierra.
Nice, I will publish updated binaries in the new release then.

Created #12 to fix this properly.

**Comment by romaincointepas** [comment]
Could you share the updated make-mac64-deps.sh used to build boram 0.3.2?

**Comment by Kagami** [comment]
Pushed latest version which uses ffmpeg from HEAD.
For 0.3.2 I used fixed Formula (`brew edit ffmpeg` → add `--disable-videotoolbox`).
